# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.


[[main]]
  name = "Repositórios"
  url = "#repositorios"
  weight = 15

[[main]]
  name = "Posts/blog"
  url = "https://beamilz.netlify.app/"
  weight = 20

[[main]]
  name = "Palestras/Talks "
  url = "https://beatrizmilz.github.io/slidesR/"
  weight = 25


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
 [[main]]
    name = "CV/Resumé  "
    url = "https://beatrizmilz.github.io/resume/index.html"
    weight = 70
