# blogdown::hugo_build()

baseurl = "https://beatrizmilz.github.io/"
languageCode = "en-us"
title = "Beatriz Milz"
theme = "hugo-lithium"
googleAnalytics = "UA-142617419-1"
disqusShortname = "beatriz_milz"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    pre = "fas fa-home"
    name = ""
    url = "https://beatrizmilz.github.io/"
    weight = 1

[[menu.main]]
    name = "Sobre/About"
    url = "/about/"
    weight = 2
    
[[menu.main]]
    name = "Apresentações/Presentations"
    url = "/slides/" 
    weight = 3
    
[[menu.main]]
    name = "Contato/Contact"
    url = "/contact/" 
    weight = 4    
    
[[menu.main]]
    name = "CV/Resume"
    url = "https://beatrizmilz.github.io/resume/index.pdf"
    weight = 5

[params]
    description = "Página pessoal de Beatriz Milz"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
   # favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 100
    height = 100
    alt = "Logo"

